## application name
spring:
  application:
    name: statemachine-server

server:
  port: 8999

## 日志配置
logging:
  config: classpath:logs/logback-spring.xml
  path: /Users/star/logs
  level:
    # 全局日志级别
    default: INFO
    # 项目日志级别
    project: INFO
    # mybatis日志级别
    mybatis: DEBUG

---
#控制台输出彩色
spring:
  output:
    ansi:
      enabled: always
## ------------------------------业务相关配置写到下面-------------------------